# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FastCirSil <- function(x, y, b, c) {
    .Call(`_CircularSilhouette_FastCirSil`, x, y, b, c)
}

linearsil <- function(points, cluster) {
    .Call(`_CircularSilhouette_linearsil`, points, cluster)
}

slowsil <- function(x, y, b, c) {
    .Call(`_CircularSilhouette_slowsil`, x, y, b, c)
}

